### ISSUE TITLE
Brackets not auto-detecting twig file type

### ISSUE THREAD

**Issue by cmarydai** [Athorcis/brackets-git#3]
Twig files are not automatically detected in Brackets

**Comment by Athorcis** [comment]
What is the extension of your twig files ?

**Comment by cmarydai** [comment]
Here is an example of one 10-interface-feedback.twig

**Comment by Athorcis** [comment]
I looked into Brackets and i found out why you experienced this issue:
In Brackets once a language has registered a file extension, this language is defined as the default language for the file extension and only the user can change it, extensions are not allowed to override a default language.

The problem is that html language is already registered as the default language for twig files.
The good news is, you can change the default language for an extension really easily to change, open one of your twig files in Brackets then switch the language to Twig and then click on the button which is at the top of the language menu (it says "Set as Default for .TWIG Files")

**Comment by cmarydai** [comment]
Thank you!
